//Action types for the questions logic
export const INCREMENT_TOTAL_CORRECT = "INCREMENT_TOTAL_CORRECT";
export const TOTAL_QUESTIONS_NUMBER = "TOTAL_QUESTIONS_NUMBER";
export const RESET_CORRECT_NUMBER = "RESET_CORRECT_NUMBER";
export const SAVE_FETCHED_QUESTIONS = "SAVE_FETCHED_QUESTIONS";
