//Action types for the questions logic
export const INCREMENT_TOTAL_CORRECT = "INCREMENT_TOTAL_CORRECT";
export const TOTAL_QUESTIONS_NUMBER = "TOTAL_QUESTIONS_NUMBER";
export const SAVE_FETCHED_QUESTIONS = "SAVE_FETCHED_QUESTIONS";
export const SAVE_ANSWER = "SAVE_ANSWER";
export const RESET_QUIZ = "RESET_QUIZ,";
